### ISSUE TITLE
lien designers wtf

### ISSUE THREAD

**Issue by nicolasdb** [chic-europecreative/chic-europecreative.github.io#2]
I found 2 errors here
http://www.chic-europecreative.eu/page4.html?nocache=82

1. the link for Dewi Origami is broken because there is to much data in the link
The link on the page is well writed but send to _http://dewiorigami.com/%C2%A0_  which doesn't exist. 
The link should be **http://dewiorigami.com/**
2. the last link "en savoir plus: " should be this one
https://github.com/openfab-lab/chic2.0/wiki
instead of 
https://github.com/openfab-lab/chic2.0/commit/e3b2b1559aff46f7008c51e8df063aed767703b2

I'm not surprise if nobody understand how to read that.... it's a very specific way to check changes between file versions. ^^' 

# To do:
Who is in charge of that? 
Make the change. 
-warning- the last one will or should be a link to the new website/github.io more readable and complete

**Comment by phmignard** [comment]
I'm sending this to our webdesigner !
