### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by phmignard** [chic-europecreative/chic-europecreative.github.io#6]
Here are the projet/partners/Europe logos !

![chico](https://user-images.githubusercontent.com/33860632/35849877-63f3c7a0-0b23-11e8-8e00-43966baa08af.jpg)
![cite-de-larchitecture-logo](https://user-images.githubusercontent.com/33860632/35849890-6bc2759e-0b23-11e8-814b-5b40d5c2dd57.png)
![logo explora](https://user-images.githubusercontent.com/33860632/35849917-78d88e26-0b23-11e8-8e03-9b9a5cba2d26.jpg)
![logo openfab](https://user-images.githubusercontent.com/33860632/35849923-7b24765e-0b23-11e8-9379-5c25b3198107.jpg)
![minga](https://user-images.githubusercontent.com/33860632/35849928-7e028546-0b23-11e8-8496-e1ea2e4e566c.jpg)
![plaine_commune logo couleurs](https://user-images.githubusercontent.com/33860632/35849935-8216de52-0b23-11e8-996b-02804ba4ebc3.jpg)
![conservas](https://user-images.githubusercontent.com/33860632/35849954-8efcf034-0b23-11e8-9495-7b1509c47e9d.gif)
![liepaja_logo_iestadem_reverss_](https://user-images.githubusercontent.com/33860632/35849972-9b5f3d5a-0b23-11e8-8bae-df738a899682.png)
![eu_flag_creative_europe_co_funded_pos_ rgb _right](https://user-images.githubusercontent.com/33860632/35850002-bbe525f8-0b23-11e8-803d-0038e6e5aa4e.jpg)

**Comment by nicolasdb** [comment]
Nice. 

:)
