### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by phmignard** [chic-europecreative/chic-europecreative.github.io#7]
Il faudrait insérer le logo ci-dessous quelque part, mais point n'y parvient...

https://user-images.githubusercontent.com/33860632/35850002-bbe525f8-0b23-11e8-803d-0038e6e5aa4e.jpg

**Comment by nicolasdb** [comment]
La modif de homepage se fait dans le fichier index.md à la racine
`/chic-europecreative.github.io/index.md`

**Comment by phmignard** [comment]
Merci :)
