### ISSUE TITLE
Page "About"

### ISSUE THREAD

**Issue by phmignard** [chic-europecreative/chic-europecreative.github.io#8]
Même problème qu'avec la home : mettre le logo "cofunded", etc. !

![img](https://user-images.githubusercontent.com/33860632/35850002-bbe525f8-0b23-11e8-803d-0038e6e5aa4e.jpg)

**Comment by nicolasdb** [comment]
ok, c'est ajouté. 
Le about.md est dans le dossier `chic-europecreative.github.io/_pages/about.md`
